/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Epoca {
  descricao: string;
  id: Generated<string>;
}

export interface Equipa {
  descricao: string | null;
  id: Generated<string>;
}

export interface Jogo {
  descricao: string | null;
  golos1: number;
  golos2: number;
  id: Generated<string>;
  id_epoca: string;
  id_equipa1: string;
  id_equipa2: string;
  titulo: string;
  data: Date
  foto: string
}

export interface DB {
  epoca: Epoca;
  equipa: Equipa;
  jogo: Jogo;
}
